-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBDwTQR1c/Qso5x4P
lyZIuIZ6TQroXcO6jJo0Vu/mdbGgCgYIKoZIzj0DAQehRANCAARHTemw7RV/nHXA
Ms0SU0NiPuKwt2ux5sLfS2m+yJUUUFeE2+7n34c3dOVVEYF3fx8RKqu3NQswCLdg
arKadjCV
-----END PRIVATE KEY-----